"""``arailctl nucleus plan`` — write a domain.yaml template, or preflight an
existing one.

Two forms (ARCHITECTURE.md §3 "plan without Buddy"):
    plan "<intent>" --name <slug>   write configs/domains/<slug>.yaml from a
                                     template with defaults; no interview —
                                     the future Buddy nucleus-partner skill
                                     (item 4, deferred) calls this same API.
    plan <slug>                     preflight-only: load the existing domain
                                     and print its plan (preflight wiring
                                     lands in commit 8; until then this just
                                     confirms the domain loads).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional, Sequence

from arail.nucleus.domain import _DOMAINS_DIR, _SLUG_RE, load_domain
from arail.nucleus.errors import DomainConfigError

_TEMPLATE = """\
# Model Forge domain — generated by `arailctl nucleus plan "{intent}" --name {slug}`.
# Edit freely; every field here is validated by `arail.nucleus.domain` on
# the next `plan`/`stage`/`build`. See docs/nucleus.md for the field guide.

student:
  base: qwen2.5-3b-instruct   # must resolve under $ARAIL_MODELS_DIR and be < 8B

teacher:
  profile: local
  model: auto

runtime: queuellm

corpus:
  sources:
    - git:REPLACE_ME
  cutoff: "{cutoff}"

eval:
  cert_set: frozen
  eyeball_prompts: {slug}.eyeball.txt
  dev_fraction: 0.1
  cert_n: 800

fidelity:
  target: 0.75

distill:
  top_n: 20

shard: qkz-{slug}
"""

_EYEBALL_TEMPLATE = "\n".join(f"REPLACE ME: eyeball prompt {i}" for i in range(1, 11)) + "\n"


def _today_iso() -> str:
    from datetime import date

    return date.today().isoformat()


def write_domain_template(intent: str, slug: str, *, domains_dir: Optional[Path] = None) -> Path:
    if not _SLUG_RE.match(slug or ""):
        raise DomainConfigError(f"--name must match ^[a-z0-9][a-z0-9-]{{0,62}}$, got {slug!r}")

    domains_dir = Path(domains_dir) if domains_dir else _DOMAINS_DIR
    domains_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = domains_dir / f"{slug}.yaml"
    if yaml_path.exists():
        raise DomainConfigError(f"{yaml_path} already exists — edit it directly or pick another --name")

    yaml_path.write_text(_TEMPLATE.format(intent=intent, slug=slug, cutoff=_today_iso()))
    eyeball_path = domains_dir / f"{slug}.eyeball.txt"
    if not eyeball_path.exists():
        eyeball_path.write_text(_EYEBALL_TEMPLATE)
    return yaml_path


def _parse_args(argv: Sequence[str]) -> dict:
    if not argv:
        raise DomainConfigError('usage: nucleus plan "<intent>" --name <slug>  |  nucleus plan <slug>')

    if len(argv) >= 3 and argv[1] == "--name":
        return {"mode": "create", "intent": argv[0], "slug": argv[2]}
    if len(argv) == 1:
        return {"mode": "preflight", "slug": argv[0]}
    raise DomainConfigError('usage: nucleus plan "<intent>" --name <slug>  |  nucleus plan <slug>')


def run(argv: Sequence[str]) -> int:
    parsed = _parse_args(argv)
    if parsed["mode"] == "create":
        path = write_domain_template(parsed["intent"], parsed["slug"])
        sys.stdout.write(f"wrote {path}\n")
        sys.stdout.write(
            "edit corpus.sources (REPLACE_ME) and the .eyeball.txt prompts, "
            "then `arailctl nucleus stage` and `arailctl nucleus plan "
            f"{parsed['slug']}` to preflight.\n"
        )
        return 0

    domain = load_domain(parsed["slug"])
    sys.stdout.write(f"domain {domain.name!r} loads cleanly (shard {domain.shard}).\n")
    sys.stdout.write(
        "preflight memory-plan output lands with the preflight module "
        "(ARCHITECTURE.md §10 commit 8) — not yet available.\n"
    )
    return 0
